name: import-gpg

on:
  push:
    branches: main

jobs:
  import-gpg:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: import gpg private key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" > ./private_key.gpg
          gpg --batch --yes --pinentry-mode loopback --import private_key.gpg
      -
        name: reveal secret
        run: |
          sudo apt install git-secret
          git secret --version
          git secret reveal -p ${{ secrets.GPG_PASSPHRASE }}
          ls