name: import-gpg

on:
  push:
    branches: main

jobs:
  import-gpg:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      -
        name: List keys
        run: gpg -K
      -
        name: reveal secret
        run:
            sudo apt-get install -y git-secret
            git secret reveal -p $(echo $GPG_PASSPHRASE | sed 's/./& /g')